-- Supabase Schema Migration (Run in SQL Editor)
-- Converts Legacy Schema to Supabase-compatible (UUIDs for Users)

-- 1. Public Profiles (Mirrors auth.users)
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email text,
    name text,
    currency_symbol text DEFAULT 'AUD',
    is_email_verified boolean DEFAULT false,
    token_version integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    household_id integer,
    mfa_enabled boolean DEFAULT false,
    mfa_secret text,
    mfa_backup_codes text
);

-- 2. Households
CREATE TABLE IF NOT EXISTS public.households (
    id bigint generated by default as identity primary key,
    name text,
    created_at timestamp with time zone default now(),
    owner_id uuid references public.users(id)
);

-- 3. Household Members (Spender Profiles)
CREATE TABLE IF NOT EXISTS public.household_members (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id),
    name text,
    color text default '#6366f1',
    avatar text default 'User',
    created_at timestamp with time zone default now()
);

-- 4. Accounts
CREATE TABLE IF NOT EXISTS public.accounts (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id),
    name text,
    type text,
    category text,
    balance double precision default 0.0,
    is_active boolean default true,
    connection_id text,
    target_balance double precision,
    target_date date
);

-- 5. Budget Buckets
CREATE TABLE IF NOT EXISTS public.budget_buckets (
    id bigint generated by default as identity primary key,
    name text,
    icon_name text default 'Wallet',
    user_id uuid references public.users(id),
    is_shared boolean default false,
    is_rollover boolean default false,
    is_transfer boolean default false,
    is_investment boolean default false,
    is_hidden boolean default false,
    is_one_off boolean default false,
    is_group_budget boolean default false,
    "group" text default 'Discretionary',
    parent_id bigint references public.budget_buckets(id),
    display_order integer default 0,
    target_amount double precision,
    target_date date
);

-- 6. Goals
CREATE TABLE IF NOT EXISTS public.goals (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id),
    name text,
    target_amount double precision,
    target_date date,
    linked_account_id bigint references public.accounts(id)
);

-- 7. Transactions
CREATE TABLE IF NOT EXISTS public.transactions (
    id bigint generated by default as identity primary key,
    date timestamp with time zone,
    description text,
    raw_description text,
    amount double precision,
    category_confidence double precision default 0.0,
    is_verified boolean default false,
    bucket_id bigint references public.budget_buckets(id),
    user_id uuid references public.users(id),
    parent_transaction_id bigint references public.transactions(id),
    spender text default 'Joint',
    goal_id bigint references public.goals(id),
    account_id bigint references public.accounts(id),
    external_id text,
    transaction_hash text,
    assigned_to text,
    tags text,
    notes text
);

-- 8. Subscriptions
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id),
    name text,
    amount double precision,
    type text default 'Expense',
    frequency text,
    next_due_date date,
    is_active boolean default true,
    description_keyword text,
    bucket_id bigint references public.budget_buckets(id),
    parent_id bigint references public.subscriptions(id)
);

-- 9. Household Users (Link Table)
CREATE TABLE IF NOT EXISTS public.household_users (
    id bigint generated by default as identity primary key,
    household_id bigint references public.households(id),
    user_id uuid references public.users(id),
    member_id bigint references public.household_members(id),
    role text default 'member',
    status text default 'active',
    invited_at timestamp with time zone default now(),
    joined_at timestamp with time zone
);

-- 10. Household Invites
CREATE TABLE IF NOT EXISTS public.household_invites (
    id bigint generated by default as identity primary key,
    household_id bigint references public.households(id),
    email text,
    token_hash text,
    role text default 'member',
    expires_at timestamp with time zone,
    accepted_at timestamp with time zone,
    invited_by_id uuid references public.users(id),
    created_at timestamp with time zone default now()
);

-- 11. Api Keys
CREATE TABLE IF NOT EXISTS public.api_keys (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id),
    name text,
    key_prefix text,
    key_hash text,
    scopes text default 'read',
    is_active boolean default true,
    expires_at timestamp with time zone,
    last_used_at timestamp with time zone,
    created_at timestamp with time zone default now(),
    rate_limit_requests integer default 1000,
    rate_limit_remaining integer default 1000,
    rate_limit_reset_at timestamp with time zone
);

-- 12. Notification Settings
CREATE TABLE IF NOT EXISTS public.notification_settings (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id),
    budget_alerts boolean default true,
    bill_reminders boolean default true,
    goal_milestones boolean default true,
    bill_reminder_days integer default 3
);

-- 13. Notifications
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id),
    type text,
    message text,
    is_read boolean default false,
    created_at timestamp with time zone default now(),
    meta_data text
);

-- 14. Investment Holdings
CREATE TABLE IF NOT EXISTS public.investment_holdings (
    id bigint generated by default as identity primary key,
    account_id bigint references public.accounts(id),
    ticker text,
    name text,
    quantity double precision,
    price double precision,
    cost_basis double precision,
    currency text default 'USD',
    exchange_rate double precision default 1.0,
    value double precision,
    asset_type text default 'Stock',
    sector text
);

-- 15. Net Worth Snapshots
CREATE TABLE IF NOT EXISTS public.net_worth_snapshots (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id),
    date date,
    total_assets double precision,
    total_liabilities double precision,
    net_worth double precision
);

-- 16. Account Balances
CREATE TABLE IF NOT EXISTS public.account_balances (
    snapshot_id bigint references public.net_worth_snapshots(id),
    account_id bigint references public.accounts(id),
    balance double precision,
    PRIMARY KEY (snapshot_id, account_id)
);

-- 17. Categorization Rules
CREATE TABLE IF NOT EXISTS public.categorization_rules (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id),
    bucket_id bigint references public.budget_buckets(id),
    keywords text,
    priority integer default 0,
    min_amount double precision,
    max_amount double precision,
    apply_tags text,
    mark_for_review boolean default false,
    assign_to text
);

-- 18. Budget Limits
CREATE TABLE IF NOT EXISTS public.budget_limits (
    id bigint generated by default as identity primary key,
    bucket_id bigint references public.budget_buckets(id),
    member_id bigint references public.household_members(id),
    amount double precision default 0.0
);

-- 19. Ignored Rule Patterns
CREATE TABLE IF NOT EXISTS public.ignored_rule_patterns (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id),
    keyword text,
    created_at timestamp with time zone default now()
);

-- 20. Category Goals
CREATE TABLE IF NOT EXISTS public.category_goals (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id),
    bucket_id bigint references public.budget_buckets(id),
    target_amount double precision,
    start_date date default now()
);

-- 21. Bucket Tags (Link Table)
CREATE TABLE IF NOT EXISTS public.tags (
    id bigint generated by default as identity primary key,
    name text unique
);

CREATE TABLE IF NOT EXISTS public.bucket_tags (
    bucket_id bigint references public.budget_buckets(id),
    tag_id bigint references public.tags(id),
    PRIMARY KEY (bucket_id, tag_id)
);

-- 22. Tax Settings
CREATE TABLE IF NOT EXISTS public.tax_settings (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id),
    filing_status text default 'Resident',
    use_standard_deduction boolean default false,
    custom_deduction double precision default 0.0,
    state text default 'VIC'
);

-- Enable RLS on all tables (Best Practice)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.households ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
-- Add policies later or now (Generic owner access)

CREATE POLICY "Users see their own profile" ON public.users FOR ALL USING (auth.uid() = id);

-- Create a Trigger to sync changes from public.users back to auth.users if needed? 
-- Or assume auth.users is master and we only sync down?
-- For now, migration populated data.
